# Generated by Django 3.2 on 2024-11-08 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='La descripción debe tener al menos 5 caracteres.')])),
                ('estado', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El estado solo debe contener letras y espacios.', regex='^[A-Za-z ]+$')])),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text=" (ej.'912345678').", max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener 9 dígitos.', regex='^\\d{9}$')]),
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_productos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad debe ser al menos 1.'), django.core.validators.MaxValueValidator(100, message='La cantidad no debe superar las 100 unidades.')])),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVenta.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVenta.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVenta.cliente'),
        ),
    ]
