# Generated by Django 3.2 on 2024-11-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVenta', '0002_auto_20241108_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoProducto',
        ),
    ]
