# Generated by Django 3.2 on 2024-11-09 01:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVenta', '0003_auto_20241108_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_productos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La cantidad debe ser al menos 1.')])),
                ('descripcion', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('estado', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVenta.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVenta.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVenta.producto')),
            ],
        ),
    ]
