# Generated by Django 3.2 on 2024-11-12 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVenta', '0004_pedido_pedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Enviado', 'Enviado'), ('Completado', 'Completado')], default='En proceso', max_length=20, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
